/*******************************************************************************
The content of this file includes portions of the AUDIOKINETIC Wwise Technology
released in source code form as part of the SDK installer package.

Commercial License Usage

Licensees holding valid commercial licenses to the AUDIOKINETIC Wwise Technology
may use this file in accordance with the end user license agreement provided 
with the software or, alternatively, in accordance with the terms contained in a
written agreement between you and Audiokinetic Inc.

  Version: v2017.2.6  Build: 6636
  Copyright (c) 2006-2018 Audiokinetic Inc.
*******************************************************************************/
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Perforce.rc
//
#define IDI_PERFORCE_STATUS_OTHER_CHECKOUT 5
#define IDD_FILE_RENAME                 4000
#define IDC_NEW_FILE_NAME               4002
#define IDC_NEW_FILE_PATH               4003
#define IDD_PERFORCE_DESCRIPTION        4006
#define IDC_DESCRIPTION                 4007
#define IDC_CHECK_OUT_AFTER_SUBMIT      4008
#define IDC_CHECK_CHECKOUT              4008
#define IDC_CHECK_ADD                   4009
#define ID_OK                           4010
#define ID_NO                           4011
#define ID_CANCEL                       4012
#define IDD_PERFORCE_CONFIG             4013
#define IDC_FILELIST                    4013
#define IDC_EDIT_CLIENT                 4014
#define IDC_TOCHECKOUT_STATIC           4014
#define IDC_EDIT_PORT                   4015
#define IDC_EDIT_HOST                   4016
#define IDC_EDIT_USER                   4017
#define IDI_PERFORCE_STATUS_ADDED       4017
#define IDD_PERFORCE_ONNEWFILES         4018
#define IDC_EDIT_SERVER                 4018
//#define IDS_PERFORCE_ICONS_TOOLTIP_NOT_CHECKED_OUT 4019
#define IDD_PERFORCE_CHECKOUTFILES      4019
#define IDC_CHECK1                      4019
#define IDC_WAVEVIEWER_DIFF_CHECK       4019
//#define IDS_PERFORCE_ICONS_TOOLTIP_CHECKED_OUT 4020
#define IDD_LONG_OPERATION_DIALOG       4020
#define IDI_PERFORCE_STATUS_NOT_CHECKED_OUT 4021
//#define IDS_PERFORCE_ICONS_TOOLTIP_ADDED 4021
#define IDI_PERFORCE_STATUS_CHECKED_OUT 4022
//#define IDS_PERFORCE_OPERATION_UPDATEALL 4022
//#define IDS_PERFORCE_ICONS_TOOLTIP_OTHER_CHECKOUT 4023
#define IDI_PERFORCE_STATUS_BOTH_CHECKOUT 4023
//#define IDS_PERFORCE_OPERATION_GETLATESTVERSION 4024
//#define IDS_PERFORCE_OPERATION_SUBMIT   4025
//#define IDS_PERFORCE_OPERATION_CHECKOUT 4026
//#define IDS_PERFORCE_OPERATION_ADD      4027
//#define IDS_PERFORCE_OPERATION_DELETE   4028
//#define IDS_PERFORCE_OPERATION_RENAME   4029
//#define IDS_PERFORCE_OPERATION_REVERT   4030
// MCTAG_NOT_IN_STRING_TABLE: #define IDS_PERFORCE_ICONS_TOOLTIP_BOTH_CHECKOUT2 4031
//#define IDS_PERFORCE_ICONS_TOOLTIP_BOTH_CHECKOUT 4031
//#define IDS_PERFORCE_NAME               4032
//#define IDS_PERFORCE_LOGIN_CAPTION      4033
//#define IDS_PERFORCE_OPERATION_MOVE     4034
//#define IDS_PERFORCE_CANT_DELETE_OPENED 4035
//#define IDS_PERFORCE_MOVE_ERROR         4036
//#define IDS_PERFORCE_MOVE_SUCCESS       4037
//#define IDS_PERFORCE_STATUS_MODIFIED    4038
//#define IDS_PERFORCE_STATUS_LOCAL_ONLY  4039
//#define IDS_PERFORCE_STATUS_ONSERVER    4040
//#define IDS_PERFORCE_DELETE_ERROR       4041
//#define IDS_PERFORCE_STATUS_ALREADY_ON_SERVER 4042
//#define IDS_PERFORCE_DELETE_SUCCESS     4043
//#define IDS_PERFORCE_RENAME_ERROR       4044
//#define IDS_PERFORCE_RENAME_SUCCESS     4045
//#define IDS_PERFORCE_RENAME_FILE_EXIST  4046
//#define IDS_PERFORCE_STATUS_OUTDATED    4047
//#define IDS_PERFORCE_STATUS_UNRESOLVED  4048
//#define IDS_PERFORCE_STATUS_LOCK        4049
//#define IDS_PERFORCE_OPERATION_HISTORY  4050
//#define IDS_PERFORCE_STATUS_MISSING     4051
//#define IDS_PERFORCE_REVERT_CONFIRMATION_QUESTION 4052
//#define IDS_PERFORCE_ERROR_MESSAGE      4053
//#define IDS_PERFORCE_OPERATION_LOCK     4055
//#define IDS_PERFORCE_OPERATION_UNLOCK   4056
//#define IDS_PERFORCE_OPERATION_DIFF     4057
//#define IDS_PERFORCE_OPERATION_RESOLVE  4058
//#define IDS_PERFORCE_DIFF_FILES_IDENTICAL_MESSAGE 4060
//#define IDS_PERFORCE_RESOLVE_ACCEPT_CAPTION 4061
//#define IDS_PERFORCE_DESCRIPTION_MESSAGE 4062
//#define IDS_PERFORCE_RENAME_MESSAGE     4064
//#define IDS_PERFORCE_RENAME_CAPTION     4065
//#define IDS_PERFORCE_RESOLVE_ACCEPT_MESSAGE 4066
//#define IDS_PERFORCE_RESOLVE_ERROR_MERGE_CAPTION 4067
//#define IDS_PERFORCE_RESOLVE_ERROR_MERGE_MESSAGE 4068
//#define IDS_PERFORCE_MESSAGEBOX_CAPTION 4069
//#define IDS_PERFORCE_CONFIG_MESSAGE     4070
//#define IDS_PERFORCE_DIFF_ERROR_MESSAGE 4072
//#define IDS_DELETE_CONFIRMATION         4073
//#define IDS_DELETE_CONFIRMATION_CAPTION 4074
//#define IDS_MOVE_FAILED_FILE_ALREADY_EXIST 4075
//#define IDS_MOVE_FAILED_NAME_CONFLICT   4076
//#define IDS_SELECT_MOVE_FOLDER          4077
#define IDI_PERFORCE_STATUS_OUTDATED_OTHER_CHECKOUT 4078
#define IDI_PERFORCE_STATUS_OUTDATED_NOT_CHECKED_OUT 4079
#define IDI_PERFORCE_STATUS_OUTDATED_CHECKED_OUT 4080
#define IDI_PERFORCE_STATUS_OUTDATED_BOTH_CHECKOUT 4081
//#define IDS_PERFORCE_ICONS_TOOLTIP_OUTDATED_NOT_CHECKED_OUT 4082
//#define IDS_PERFORCE_ICONS_TOOLTIP_OUTDATED_CHECKED_OUT 4083
//#define IDS_PERFORCE_ICONS_TOOLTIP_OUTDATED_BOTH_CHECKOUT 4084
//#define IDS_PERFORCE_ICONS_TOOLTIP_OUTDATED_OTHER_CHECKOUT 4085
#define IDC_DIFF_TOOL                   5008
#define IDC_DIFF_BROWSE                 5009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        4021
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         4020
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
