//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilePackager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilePackager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiokinetic File Packager - {0}.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all packages.
        /// </summary>
        internal static string BuildAllPackages {
            get {
                return ResourceManager.GetString("BuildAllPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0}.
        /// </summary>
        internal static string BuildNumber {
            get {
                return ResourceManager.GetString("BuildNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate selected packages.
        /// </summary>
        internal static string BuildSelectedPackages {
            get {
                return ResourceManager.GetString("BuildSelectedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find the help file &apos;{0}&apos;..
        /// </summary>
        internal static string CantFindHelpFile {
            get {
                return ResourceManager.GetString("CantFindHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the file {0}..
        /// </summary>
        internal static string CouldNotFindInfoFile {
            get {
                return ResourceManager.GetString("CouldNotFindInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SoundBanksInfo.xsd.  Please make sure the FilePackager binaries are in the bin\tools directory..
        /// </summary>
        internal static string CouldNotFindXmlSchema {
            get {
                return ResourceManager.GetString("CouldNotFindXmlSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load info file: {0}.
        /// </summary>
        internal static string CouldNotLoadInfoFile {
            get {
                return ResourceManager.GetString("CouldNotLoadInfoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create language packages.
        /// </summary>
        internal static string CreateLanguagePackages {
            get {
                return ResourceManager.GetString("CreateLanguagePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.pck.
        /// </summary>
        internal static string DefaultPackageName {
            get {
                return ResourceManager.GetString("DefaultPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the change to your project?.
        /// </summary>
        internal static string DoYouWantToSave {
            get {
                return ResourceManager.GetString("DoYouWantToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not execute the command &apos;{0}&apos;.  Please review the following error(s):
        ///
        ///{1}.
        /// </summary>
        internal static string ErrorExecutingCommand {
            get {
                return ResourceManager.GetString("ErrorExecutingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while loading project: {0}.
        /// </summary>
        internal static string ErrorLoadingProject {
            get {
                return ResourceManager.GetString("ErrorLoadingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving the project: {0}.
        /// </summary>
        internal static string ErrorSavingProject {
            get {
                return ResourceManager.GetString("ErrorSavingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string FormatByteSize {
            get {
                return ResourceManager.GetString("FormatByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string FormatGigaByteSize {
            get {
                return ResourceManager.GetString("FormatGigaByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string FormatKiloByteSize {
            get {
                return ResourceManager.GetString("FormatKiloByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string FormatMegaByteSize {
            get {
                return ResourceManager.GetString("FormatMegaByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string FormatTeraByteSize {
            get {
                return ResourceManager.GetString("FormatTeraByteSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze selected packages.
        /// </summary>
        internal static string FreezeSelectedPackages {
            get {
                return ResourceManager.GetString("FreezeSelectedPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string InclusionModeAllFiles {
            get {
                return ResourceManager.GetString("InclusionModeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBank only.
        /// </summary>
        internal static string InclusionModeBank {
            get {
                return ResourceManager.GetString("InclusionModeBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBank and loose media.
        /// </summary>
        internal static string InclusionModeBankAndLooseMedia {
            get {
                return ResourceManager.GetString("InclusionModeBankAndLooseMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SoundBank and streamed files.
        /// </summary>
        internal static string InclusionModeBankAndStreams {
            get {
                return ResourceManager.GetString("InclusionModeBankAndStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External source.
        /// </summary>
        internal static string InclusionModeExternal {
            get {
                return ResourceManager.GetString("InclusionModeExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string InclusionModeInvalid {
            get {
                return ResourceManager.GetString("InclusionModeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loose media.
        /// </summary>
        internal static string InclusionModeLooseMedia {
            get {
                return ResourceManager.GetString("InclusionModeLooseMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamed files.
        /// </summary>
        internal static string InclusionModeStreams {
            get {
                return ResourceManager.GetString("InclusionModeStreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamed files and loose media.
        /// </summary>
        internal static string InclusionModeStreamsAndLooseMedia {
            get {
                return ResourceManager.GetString("InclusionModeStreamsAndLooseMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package name: &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string InvalidPackageName {
            get {
                return ResourceManager.GetString("InvalidPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1}{2} - {0}.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New package {0}.pck.
        /// </summary>
        internal static string NewPackageName {
            get {
                return ResourceManager.GetString("NewPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing....
        /// </summary>
        internal static string PreparingBuild {
            get {
                return ResourceManager.GetString("PreparingBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as project.
        /// </summary>
        internal static string SaveAsProject {
            get {
                return ResourceManager.GetString("SaveAsProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save project.
        /// </summary>
        internal static string SaveProject {
            get {
                return ResourceManager.GetString("SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining files inserted here.
        /// </summary>
        internal static string UnlayoutItemsName {
            get {
                return ResourceManager.GetString("UnlayoutItemsName", resourceCulture);
            }
        }
    }
}
